//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHP_SRePS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int salesID { get; set; }
        public Nullable<int> productID { get; set; }
        public System.DateTime saleDate { get; set; }
        public Nullable<int> salesQuantity { get; set; }
        public string employee { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
